### ISSUE TITLE
Plan Milestone 1

### ISSUE THREAD

**Issue by maxamey** [maxamey/triviato#1]

**Comment by maxamey** [comment]
- [x] Research apps that do this
- [x] Model data based on research
- [ ] Build UI for creating game
- [x] Connect to Firebase 
- [ ] Save data to Firebase
