### ISSUE TITLE
Plan Milestone 3

### ISSUE THREAD

**Issue by maxamey** [maxamey/triviato#11]

**Comment by maxamey** [comment]
- [x] plan active game
- [x] save data to firebase
- [ ] build dynamic active game component using data from firebase
- [ ] make questions in nav link to edit view with populated form
