### ISSUE TITLE
Plan Milestone 2

### ISSUE THREAD

**Issue by maxamey** [maxamey/triviato#12]
Things I didn't pushed from Milestone 1 and new tasks based on iteration overview

**Comment by maxamey** [comment]
- [ ] Testing create component
- [ ] Save data to firebase instead of state
- [ ] Refine loop over object to better insert questions
- [ ] Refine nav tree functionality
  - [ ] Hamburger menu?
  - [ ] button link for create new question
  - [ ] button link for edit existing question
- [ ] Start making style decisions
- [ ] Build boilerplate for active game component
- [ ] Plan active game component
- [ ] Make question links in nav tree link to re-edit them
