### ISSUE TITLE
Plan Milestone 5

### ISSUE THREAD

**Issue by maxamey** [maxamey/triviato#9]
- [ ] Index page
  - [ ] link to create game
  - [ ] list of links to active game
- [ ] Routing
- [ ] Style create page
- [ ] Style active game page
- [ ] Style index page
- [ ] Refine create page features
